apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: loykonen-matveev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: anmatveev9303/fastapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: fastapi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: loykonen-matveev
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet # Заменить на StatefulSet
metadata:
  name: mysql
  namespace: loykonen-matveev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: local-storage-loykonen-matveev
#   namespace: loykonen-matveev
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mysql-pv
#   namespace: loykonen-matveev
#   labels:
#     type: local
# spec:
#   storageClassName: local-storage-loykonen-matveev
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/var/lib/mysql"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql-pv-claim
# spec:
#   storageClassName: local-storage-loykonen-matveev
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi